name: ReactAppCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email ${{secrets.GIT_EMAIL}}
        git config --global user.name ${{secrets.GIT_USERNAME}}
        git remote set-url origin https://${{secrets.GIT_PERSONAL_TOKEN}}@github.com/${{secrets.GIT_USERNAME}}/rent-a-car.git
        npm run deploy
      env:
        REACT_APP_API_URL: ${{secrets.REACT_APP_API_URL}}